language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt

script:
  - python test.py

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true