language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
  global:
  - USER="travis"
  - EMAIL=""
  - REPO="PokemonSite"
  - FILES="*"
  - GH_REPO="github.com/igorfs10/${REPO}.git"
  - BRANCH="gh-pages"

install:
  - pip install -r requirements.txt

before_script:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO}
  - cd ${REPO}

script:
  - python test.py

after_success:
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add ${FILES}
  - git commit -m ${MESSAGE}
  - git push "https://${GITHUB_TOKEN}@${GH_REPO}" {BRANCH} > /dev/null 2>&1