language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
  global:
  - REPO="PokemonSite"
  - GH_REPO="github.com/igorfs10/${REPO}.git"
  - BRANCH="gh-pages"

install:
  - pip install -r requirements.txt

before_script:
  - git clone -b ${BRANCH} git://${GH_REPO}

script:
  - python generateAPI.py

after_success:
  - cp api/* ${REPO}/api
  - cd ${REPO}
  - git config user.email "travis@travis-ci.org"
  - git config user.name "travisci"
  - git add *
  - git commit -m "Travis atualizando API"
  - git push "git://${GITHUB_TOKEN}@${GH_REPO}" ${BRANCH}