language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
  global:
  - USER="travisci"
  - EMAIL="travis@travis-ci.org"
  - REPO="PokemonSite"
  - GH_REPO="github.com/igorfs10/${REPO}.git"
  - BRANCH="gh-pages"

install:
  - pip install -r requirements.txt

before_script:
  - git clone git://${GH_REPO}
  - cd ${REPO}
  - git checkout ${BRANCH}

script:
  - python test.py

after_success:
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add *
  - git commit -m "Travis atualizando API"
  - git push "https://${GITHUB_TOKEN}@${GH_REPO}" ${BRANCH}