[package]
name = "download_images"
version = "0.1.0"
authors = ["igorfs10 <igorfs10@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
photon-rs = { git = "https://github.com/silvia-odwyer/photon/" }
reqwest = { version = "^0.10", features = ["blocking"] }
rayon = "^1.4.0"